# Generated by Django 5.1.4 on 2024-12-18 12:00

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=70)),
                ('message', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='team/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('property_type', models.CharField(max_length=200)),
                ('property_name', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField()),
                ('land_use', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('MIXED USE', 'Mixed use')], default='RESIDENTIAL', max_length=20)),
                ('land_title', models.CharField(max_length=300)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('property_size', models.PositiveIntegerField()),
                ('features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CCTV CAMERA', 'Cctv Camera'), ('FAMILY LOUNGE', 'Family Lounge'), ('SWIMMING POOL', 'Swimming Pool'), ('FULLY FITTED KITCHEN', 'Fully Fitted Kitchen'), ('24/7 POWER SUPPLY', '24/7 Power Supply'), ('BALCONY VIEWS', 'Balcony Views')], max_length=92)),
                ('balconies', models.PositiveIntegerField(default=0)),
                ('serviced', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OFFPLAN', 'Offplan'), ('READYTOMOVEIN', 'Ready to Move In'), ('AVAILABLE', 'Available')], default='AVAILABLE', max_length=20)),
                ('newly_built', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('payment_plan', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('3 MONTHS', '3 Months'), ('6 MONTHS', '6 Months'), ('8 MONTHS', '8 Months'), ('10 MONTHS', '10 Months'), ('12 MONTHS', '12 Months')], max_length=46)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='core.location')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/images/')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.property')),
            ],
        ),
    ]
